#include<bits/stdc++.h>
using namespace std;

void F(string &s , int i, string res, vector<string> &ans)
{
    if( i == s.length())
    {
        ans.push_back(res);
        return;
    }

    F(s,i+1,res+s[i],ans);
    F(s,i+1,res,ans);
}


int main()
{

	#ifndef ONLINE_JUDGE
		freopen("input.txt","r",stdin);
		freopen("output.txt","w",stdout);
	#endif	
	

	/* 
	 given string we have to find out all its subsequences of it .
	 
	 IMP : A string is a subsequence of a given string that is generated by deleting some character
	 of a given string without changing its order.

	 input : abc
	 o/p : a , b , c , ab, bc , ac, abc 

	  ca --> x not allowed as we have to maintain the relative ordering .

	*/	
		string s;
		cin>>s;

		vector<string> ans;

		F(s,0,"",ans);

        for(int i=0;i<ans.size();i++)
        {
        	cout<<ans[i]<<" ";
        }
 
	return 0;

}